version: "3.9"

services:
  db:
    image: postgres16-alpine
    volumes:
      - ./postgres:/var/lib/postgresql/dev_data
    env_file: .env
  web:
    build: .
    image: iliamv/test_app:latest
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file: .env
  