version: "3.9"

services:
  db:
    image: postgres:16-alpine
    expose:
      - 5432
    volumes:
      - ./postgres:/var/lib/postgresql/dev_data
    env_file: .env
  web:
    build: .
    image: iliamv/test_app:latest
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file: .env
    volumes:
    - .:/home/app/web
  front:
    build: ./front
    image: iliamv/test_app_front:latest
    command: npm start
    volumes:
      - ./front:/home/app/front
    ports:
      - 3000:3000
  