# Generated by Django 4.2.6 on 2023-10-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers_pinger', '0003_alter_responsemodel_ping_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsemodel',
            name='ping_time',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
